# Generated by Django 2.0 on 2018-05-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20180518_0307'),
        ('service', '0009_auto_20180518_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='computing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ecommerce',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='others',
            name='user',
        ),
        migrations.RemoveField(
            model_name='television',
            name='user',
        ),
        migrations.AddField(
            model_name='apartment',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computing',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='television',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile'),
            preserve_default=False,
        ),
    ]
