# Generated by Django 2.0 on 2018-05-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20180518_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
