# Generated by Django 2.0 on 2018-05-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_remove_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division'),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division'),
        ),
    ]
